name : CI-build and push
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: dockerlogin
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build the docker image
        run: docker build -t saireka/flask-image:v1 .

      - name: push the image to dockerhub
        run: docker push saireka/flask-image:v1
